defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:14-browsers

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Run tests
          command: npm t
      - run:
          name: Code linting
          command: npm run lint -- --plugin log
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set npmrc credentials
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npx published --git-tag
  glossary:
    <<: *defaults
    steps:
      - run:
          name: Add to Glossary
          command: |
            curl --user ${CIRCLECI_API_TOKEN}: \
              --header "Content-Type: application/json" \
              --data "{\"build_parameters\":{\"TRIGGERING_REPOSITORY\":\"${CIRCLE_REPOSITORY_URL}\"}}" \
              --request POST \
              https://circleci.com/api/v1.1/project/github/fiverr/glossary/tree/master
  playground:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build playground
          command: npm run build
      - run:
          name: Publish to gh-pages
          command: curl ci-cd.net/v1/gh/pages | bash -s dist/.


experimental:
  notify:
    branches:
      only:
        - master

workflows:
  version: 2
  ci-cd:
    jobs:
      - test
      - publish:
          context: org-global
          requires:
            - test
      - glossary:
          context: org-global
          requires:
            - publish
          filters:
            branches:
              only:
                - master
      - playground:
          context: org-global
          requires:
            - publish
          filters:
            branches:
              only:
                - master
                - 2020-06-18-version-2
