defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:8-browsers

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set npmrc credentials
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm t
      - run:
          name: Code linting
          command: npm run lint
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set npmrc credentials
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npx published
  glossary:
    <<: *defaults
    steps:
      - run:
          name: Add to Glossary
          command: curl ci-cd.net/v1/gh/run | bash -s fiverr glossary master "bin/trigger.sh" $GITHUB_API_TOKEN

experimental:
  notify:
    branches:
      only:
        - master

workflows:
  version: 2
  ci-cd:
    jobs:
      - dependencies:
          context: org-global
      - test:
          requires:
            - dependencies
      - publish:
          context: org-global
          requires:
            - test
      - glossary:
          context: org-global
          requires:
            - publish
          filters:
            branches:
              only:
                - master
